[package]
name = "lab2"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
serde = { version = "1.0.210", features = ["derive"] }
serde-binary = "0.5.0"
socket2 = "0.5.7"
